name: Build and test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v2
    -   name: set up JDK 11
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '11'
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Create piano.properties
        env:
          AID: ${{ secrets.SAMPLE_AID }}
        run: echo "io.piano.aid=$AID" > sample/piano.properties
    -   name: Check codestyle
        run: ./gradlew ktlintCheck
    -   name: Build project
        run: ./gradlew testDebug sample:asDeb
