name: Publish Release

on:
  release:
    types: [created]
env:
    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v2
    -   name: set up JDK 11
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '11'
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Create piano.properties
        env:
          AID: ${{ secrets.SAMPLE_AID }}
        run: echo "io.piano.aid=$AID" > sample/piano.properties
    -   name: Upload artifacts
        run: ./gradlew publish --no-daemon --no-parallel
    -   name: Close repository
        run: ./gradlew closeAndReleaseRepository --no-daemon
